### ISSUE TITLE
Board and connector

### ISSUE THREAD

**Issue by Fnux** [arturo182/bbq10kbd_breakout#1]
Hello,

I have some trouble finding your email adress so this issue will do. I have a few questions:

  * What connector do you use on the board ? 
  * Do you have any good plan or advise to obtain/print the board ? That's something I never did.

Thanks!

**Comment by arturo182** [comment]
You can find more info about the connector here: https://github.com/arturo182/BBQ10KBD

For ordering PCBs I'd recommend https://oshpark.com if you are in US and https://aisler.net if you are in Europe.

**Comment by Fnux** [comment]
That's perfect. Thanks!
